name: essentials
main: me.icyy.essentials.Plugin
version: 1
api-version: 1.15

commands:
  gmc:
    description: Change your gamemode to creative
  gms:
    description: Change your gamemode to survival
  gmsp:
    description: Change your gamemode to spectator
  gma:
    description: Change your gamemode to adventure
  heal:
    description: Replenish your health and hunger
  fly:
    description: Enable or disable fly mode